### ISSUE TITLE
Dashboard should be doing aggregations by the event's creation date, not the date the event will be held

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/VolunteerDashboard#1]
I think it is currently doing these based on event date and not event creation date since I see data for the future.

**Comment by rapicastillo** [comment]
@saikat Maybe we can create another chart for it? One that shows when events are being created? I think setting it on the event date itself shows which weeks people have engaged/participated, so these two are showing different but helpful infos.

**Comment by coventry** [comment]
Fixed in latest version.

**Comment by saikat** [comment]
Agreed with rapi, but i think the creation date is the more important metric right now for the people we are showing this dashboard to (potential event hosts/organizers).  Thanks @coventry

**Comment by rapicastillo** [comment]
Showing the events analytics by creation date. Will create a way to show information based on creation date and event date. Thank you @coventry !!
