### ISSUE TITLE
Make data being used by dashboard be real-time

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/VolunteerDashboard#2]
This is probably something that we need to do in event-counter rather than in the dashboard, but might as well make all the issues in one place.

**Comment by saikat** [comment]
https://github.com/Bernie-2016/EventCounter is the project trying to make this happen.  I think we are almost there, just need to hook some things up.  @rapicastillo @coventry let's try to make this get all hooked up this week!

**Comment by saikat** [comment]
Refer to https://github.com/Bernie-2016/EventCounter/issues/4

**Comment by coventry** [comment]
Fixed in latest version: hourly updates.

**Comment by rapicastillo** [comment]
Fixed on frontend, now showing latest info by event creation date
