### ISSUE TITLE
Bad RSVP data

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/VolunteerDashboard#21]
@coventry is working on this I believe.  Some areas show wrong RSVP counts.  Also we should exclude official events (like rallies).

**Comment by coventry** [comment]
Both the anomalous `4vfr2` event and rallies are excluded in [this commit](https://github.com/Bernie-2016/EventCounter/commit/2cea0c002d45fb1b0e20d7c2485d27ffa630399d).  Other events can be excluded by adding them to `serve.Root.hidden_events.`
