### ISSUE TITLE
Organizers want a way to see data in a numerical format

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/VolunteerDashboard#3]
From Ben:

"Many organizers would like to see a numerical, rather than graphical, representation of the data so that they can more easily digest it and present it to others. Controls should be provided to view the data by date range."

On the phone, he also mentioned making this something that is easily printable.  For a first pass here, we can possibly just add a tab at the top to switch between graph and table view, and in the table view, break it down by week/month?

**Comment by rapicastillo** [comment]
Refactored code to be able to create tabularized data.
