### ISSUE TITLE
If I am an organizer in IL, and I select IL from the top drop-down to view IL only so I can see the detailed Regions specific to IL

### ISSUE THREAD

**Issue by Karijo35** [Bernie-2016/VolunteerDashboard#35]
If I am an organizer in IL, and I select IL from the top drop-down to view IL only so I can see the detailed Regions specific to IL, it would be really cool if, when I see a tiny number of events, allow the user to right-click/select a link to "Send email to other volunteers?".  Then a small email dialogue box could open so I can personally send an email to all the other volunteers who created those events.  Or, we could create some "standard language" emails to choose from  (e.g. Great job creating those events!  Would you consider helping me with an upcoming event?  If so, please contact me directly at xxxxxxx").  Does this make sense?  I'm trying to find a way to make this data actionable for the volunteers/organizers so they can reach others in their area without compromising privacy.  So, 1) I am assuming we have access to all of the event hosts, including their email, and 2) this function would be beneficial to the national effort, and 3) this would help although not fully alleviate, the requests from volunteers/organizers in the field to have a way to contact others.  Something to consider.

**Comment by coventry** [comment]
This would be cool, but it would also be open to extremely destructive abuse without some sort of vetting workflow for the emails.

It would be significant work on top of what we've done so far.

We can discuss this more on the slack.  If there's a strong need for something like this, I'll consider it.  But it would take a long time.
