### ISSUE TITLE
Event Types - diffs

### ISSUE THREAD

**Issue by Karijo35** [Bernie-2016/VolunteerDashboard#37]
For ease of use, I will refer back to global 'Event Types' as they appear to be whatever the title of an event may be.  It might be best for those types to match the actual types displayed under the graph to avoid confusion, as the data appears to come from two different sources.  I would strongly recommend this change as it will allow all of us to better understand the data and filter out "noise", such as "Fundraising Brunch Town Meeting".  This event should fall under "Town Meeting" type and does not need to appear as its own event.

**Comment by coventry** [comment]
The data is coming to us from a source we don't control, and it appears the early data-entry software was very liberal.  

It appears there was just one such event, on Jun 22, so hopefully this won't cause too much confusion.
