### ISSUE TITLE
Events not within date range parm

### ISSUE THREAD

**Issue by Karijo35** [Bernie-2016/VolunteerDashboard#38]
Additionally, when selecting only the "Fundraising Brunch Town Meeting" with date parameters set = 11/1/15 - 12/26/15 - the event does not appear on the graph (I assume because it is not inside the specified date parm).  For global event types, if we are going to keep those as the individually named events, then we should not display the event if it falls outside of the specific date parameters chosen.

**Comment by coventry** [comment]
There's probably a morass of special cases like this which don't significantly impair people's ability to reason from the data as represented.
