### ISSUE TITLE
Stress/Load testing?

### ISSUE THREAD

**Issue by Karijo35** [Bernie-2016/VolunteerDashboard#44]
Has anyone tried to perform this type of testing on the site yet?  If we are planning to release, you may want to understand if there is any severe degradation in performance or failure if too many users are requesting/working with the tool concurrently.

**Comment by coventry** [comment]
At this stage the communication with the backend is extremely simple and easily cached.  I don't have a lot of experience in building high-traffic websites, but for what it's worth I'll be very surprised if that's a problem.  @saikat will be able to verify this.
