### ISSUE TITLE
Data does not show up for some regions at all

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/VolunteerDashboard#5]
E.g. http://volunteer-dashboard.herokuapp.com/?state=HI

My hunch is this is an issue with the CL list of zip codes not covering everything in the US.  Or it might be that the event data is missing some information.  Either way, this is probably the biggest bug right now.

**Comment by coventry** [comment]
Largely fixed in the [latest version](http://gobernie.net:9000/src/#state=HI&startdate=2015-10-07&enddate=2015-12-07), with the analysis in extra coventry/cl-zip-codes applied in [more-cl-zipcodes.txt](https://github.com/Bernie-2016/EventCounter/blob/front-end-integration/data/more-cl-zipcodes.txt).

There are still a few zips missing.

**Comment by michelledeatrick** [comment]
The remaining issue that I see is Hawaii. There are definitely events missing from areas that are not Honolulu or even on the same island: https://go.berniesanders.com/page/event/search_results?orderby=day&state=HI&country=US&date_start=1444190400&date_end=1448773199&limit=100&radius_unit=mi

**Comment by coventry** [comment]
Thanks, Michelle.  I'll figure out why these were excluded.

**Comment by michelledeatrick** [comment]
Is it going to be possible to break these out by island? Or at least not to label all events "Honolulu" as they are currently on the charts?

**Comment by michelledeatrick** [comment]
And which are the missing zips mentioned 25 days ago? Can this be addressed? This tool is so close being ready, and so powerful. We're really grateful. But we really need all the data to be there, because otherwise it will lose  credibility with our state organizers.

**Comment by coventry** [comment]
Hi, Michelle.  As far as I can tell, the Hawaii zips are all included.  It's not clear to me from the [berniesanders.com link you gave](https://go.berniesanders.com/page/event/search_results?orderby=day&state=HI&country=US&date_start=1444190400&date_end=1448773199&limit=100&radius_unit=mi) that there are events missing.  If there is a discrepancy, can you please  give a few more details?

Breaking these events out to the different islands ought not to be a big deal.  I will give it a go.

Currently, a zip is excluded when either

1) No latitude/longitude is given.  These zips are primarily for administrative or military purposes, I believe, and can probably be safely excluded.  (And assigning them would require substantial further research.)  Or,

2) The zip is not listed as belonging to a US state.  E.g., Guam, Puerto Rico, military bases with public location data.   There is nothing stopping us from having a Guam or a Puerto Rico region, though.  That exclusion came from the CL data.  Is it worth putting them in?

There are 867 excluded zips.  To give a flavor of what's in there, I have posted a list of them to the slack channel.

**Comment by michelledeatrick** [comment]
Hi Alex, You're right. The Hawaii data is looking good--thanks for removing "Honolulu" which is waht was confusing me.

 If you can break these out by island, that would be really helpful.

And thank you for the excluded zips. That is a helpful perspective on the data.

**Comment by michelledeatrick** [comment]
I'll get back to you on the Puerto Rico/Guam issue. Good question.

**Comment by michelledeatrick** [comment]
For Hawaii, we should have: Oahu, Kauai, Maui, Big Island.  We don't need one for the little islands.

**Comment by coventry** [comment]
Since PR/Guam have no federal voting privileges, I don't think fixing that ought to be a priority for us.

**Comment by coventry** [comment]
> We don't need one for the little islands.

That's the islands in Kalawo County?  What would be the best way to assign those zips?
